[[Messages]]
  Name = "Ed"
  Text = "Knock knock."

[[Messages]]
  Name = "Sam"
  Text = "Who's there?"

[[Messages]]
  Name = "Ed"
  Text = "Go fmt."

[[Messages]]
  Name = "Sam"
  Text = "Go fmt who?"

[[Messages]]
  Name = "Ed"
  Text = "Go fmt yourself!"
